package ukt.controller;

public enum Command {
	CREATE_WORKFLOW,
	DISPLAY_KENNING_PANEL,
	CONVERT_KENNING_TO_CWL,
	RUN_CWL,
	ADD_PROCESS_WORKFLOW,
	REMOVE_PROCESS_WORKFLOW,
	ADD_SPECIFICATION_FILE,
	ADD_GRAPH_FILE,
	EXIT_APPLICATION
}
