package ukt.controller;

public enum Command {
	CREATE_WORKFLOW,
	DISPLAY_KENNING_PANEL,
	CONVERT_KENNING_TO_CWL,
	RUN_CWL,
	ADD_BASECOMMAND1_WORKFLOW,
	ADD_BASECOMMAND2_WORKFLOW,
	ADD_SPECIFICATION_FILE,
	RESET_WORKFLOW_VIEW,
	MERGE_BASECOMMAND,
	RESET_KENNING_VIEW,
	RUN_WORKFLOW,
	ADD_GRAPH_FILE,
	EXIT_APPLICATION
}
